### ISSUE TITLE
mysql のバックアップをする

### ISSUE THREAD

**Issue by snakagaw** [tsume-ha/Zoomail#78]
リリーすしたのでほしいですね...........coreserver 落ちたら終わりなので.......(本当はファイルとかもバックアップするといいかも)

Google DriveのAPIがあるので選択肢かも, 当面はノートパソコンにダウンロードとかでもいいと思います.

**Comment by tsume-ha** [comment]
サーバーでスクリプトを書いて、バックアップするようにしました。
ありがとうございます！
